// src/components/Background.tsx
import { onMount, createSignal, Component } from 'solid-js'
import { makeEventListener } from '@solid-primitives/event-listener'

export const Background: Component = () => {
  const [progress, setProgress] = createSignal<number>(0)

  onMount(() => {
    makeEventListener(window, 'scroll', () => {
      setProgress(
        document.scrollingElement.scrollTop /
          (document.scrollingElement.scrollHeight -
            document.scrollingElement.clientHeight)
      )
    })
  })

  return (
    <div
      class="pointer-events-none fixed inset-0 -z-10 container"
      style={{ '--progress': progress() * 100 + '%' }}
    >
      <div
        class="absolute rounded-lg w-60 h-60 hidden md:block rotate-[60deg] opacity-10 blur translate-y-[var(--progress)]"
        style={{
          'background-color': 'var(--color-3)',
          top: '20%',
          left: '0',
        }}
      />
      <div
        class="absolute rounded-lg w-60 h-60 rotate-[60deg] opacity-10 blur translate-y-[var(--progress)]"
        style={{
          'background-color': 'var(--color-4)',
          top: '-200px',
          right: '0',
        }}
      />
      <div
        class="absolute rounded-lg w-60 h-60 rotate-[60deg] opacity-10 blur translate-y-[var(--progress)]"
        style={{
          'background-color': 'var(--color-2)',
          top: '50%',
          right: '0',
        }}
      />
    </div>
  )
}

// src/components/Background.svelte
<script lang="ts">
  function updateParallax() {
    const percentScrolled =
      document.scrollingElement.scrollTop /
      (document.scrollingElement.scrollHeight -
        document.scrollingElement.clientHeight);
    document.body.style.setProperty(
      "--percent-scrolled",
      percentScrolled + "px"
    );
  }
</script>

<svelte:window on:scroll={updateParallax} />

<div class="container">
  <div
    class="bg-box"
    style="background-color: var(--color-3); top: 20%; left:0;"
  />
  <div
    class="bg-box"
    style="background-color: var(--color-4); right: 0; top:-200px"
  />
  <div
    class="bg-box"
    style="background-color: var(--color-2); right: 0; top:50%;"
  />
</div>

<style>
  .container {
    pointer-events: none;
    position: fixed;
    inset: 0;
  }
  .bg-box {
    z-index: var(--bg-layer);
    position: absolute;
    border-radius: var(--radius);
    height: 300px;
    width: 300px;
    transform: translateY(calc(var(--percent-scrolled, 0px) * 100))
      rotate(60deg);
    filter: blur(10px);
    opacity: 10%;
    &:first-child {
      @media (--md-n-below) {
        display: none;
      }
    }
  }
</style>
