// src/sections/Testimonials.svelte
<script lang="ts">
  import Section from "../components/Section.svelte";
  import testimonials from "../data/testimonials";
  import Testimonial from "../components/Testimonial.svelte";
  import { onMount } from "svelte";

  const CAROUSEL_TIMEOUT: number = 10000; // in milliseconds
  let scrollElement: HTMLElement;
  let childElements: HTMLElement[] = [];
  let activeIndex = 1;

  function step(dir: number) {
    activeIndex =
      (activeIndex + dir + testimonials.length) % testimonials.length;
    const { width: containerWidth } = scrollElement.getBoundingClientRect();
    const { width: cardWidth } = childElements[0]
      .querySelector(".testimonial")
      .getBoundingClientRect();
    const width = scrollElement.scrollWidth / (containerWidth / cardWidth);
    scrollElement.scrollTo({
      behavior: "smooth",
      left: (width / 2) * activeIndex,
      top: 0,
    });
  }

  onMount(() => {
    step(0);
    const interval = setInterval(() => step(1), CAROUSEL_TIMEOUT);
    return () => clearInterval(interval);
  });
</script>

<Section title="what others have to say" id="testimonials">
  <div class="testimonials" bind:this={scrollElement}>
    {#each testimonials as testimonial, index}
      <div bind:this={childElements[index]} style="display: contents">
        <Testimonial {testimonial} />
      </div>
    {/each}
  </div>
</Section>

<style>
  .testimonials {
    display: flex;
    gap: var(--gap);
    width: 100%;
    padding-top: var(--gap);
    padding-bottom: var(--gap);
    scroll-snap-type: x mandatory;
    overflow-x: auto;
    position: relative;
    /* @media (max-width: 768px) { */
    /*     flex-direction: column; */
    /* } */
  }
</style>

// src/sections/Testimonials.tsx
import { onMount, For, Component } from 'solid-js'
import testimonials from '../data/testimonials'
import { Testimonial } from '../components/Testimonial'
import styles from './Testimonial.module.css'

const CAROUSEL_TIMEOUT: number = 20000 // in milliseconds

export const Testimonials: Component = () => {
  let scrollElement: HTMLDivElement
  let childElements: HTMLDivElement[] = []
  let activeIndex = 1

  function step(dir: number) {
    activeIndex =
      (activeIndex + dir + testimonials.length) % testimonials.length
    const { width: containerWidth } = scrollElement.getBoundingClientRect()
    const { width: cardWidth } = childElements[0]
      .querySelector('[data-tag=testimonial]')!
      .getBoundingClientRect()
    const width = scrollElement.scrollWidth / (containerWidth / cardWidth)
    scrollElement.scrollTo({
      behavior: 'smooth',
      left: (width / 2) * activeIndex,
      top: 0,
    })
  }

  onMount(() => {
    step(0)
    const interval = setInterval(() => step(1), CAROUSEL_TIMEOUT)
    return () => clearInterval(interval)
  })

  return (
    <div class={styles.testimonials} ref={scrollElement!}>
      <For each={testimonials}>
        {(testimonial, index) => (
          <div ref={childElements[index()]} style="display: contents">
            <Testimonial testimonial={testimonial} data-tag="testimonial" />
          </div>
        )}
      </For>
    </div>
  )
}
